/*
  PORTFOLIO CONTENT
  This is the only file you need to edit to update the site.

  Media rules (work anywhere a media field appears):
    - Video: paste a Vimeo or YouTube link, e.g. "https://vimeo.com/123456789".
             An uploaded file also works: "media/my-project/film.mp4" (keep it small).
             Any other link (Instagram, etc.) shows as a "Watch" button.
    - Image: a local file, e.g. "media/my-project/cover.jpg", or any full image URL.
    - Leave a field as "" and the site shows a marked placeholder instead.

  To add a project: copy one { ... } block, paste it into the list, change the fields,
  and put its images in media/<slug>/.
  To hide a project without deleting it: add  hidden: true
  To link out (Instagram post, client page): add  link: "https://..."
  Vertical video (Reels, Shorts): add  aspect: "9:16"
*/

window.PORTFOLIO = {
  site: {
    name: "Fábio Araújo",
    role: "Filmmaker & Editor",
    intro: "My work combines storytelling, strategy, and technical execution.",
    email: "fabioaraujoprofissional@gmail.com",
    phone: "",             // optional, shown in Contact if filled, e.g. "+351 ..."
    location: "Lisbon, Portugal",
    showreel: "",          // when you have a reel: Vimeo or YouTube link adds a "Play reel" button to the hero
    heroStripCount: 12,    // how many film stills scroll along the bottom of the hero (featured first)
    stillsIntro: "",       // optional line next to the "Stills" heading
    stillsPerSeries: 12,   // how many photos of the selected series show in Stills (all show on the series page)
    portrait: "media/_site/portrait.jpg",
    // About: the first paragraph shows large, the rest as body text. Add or remove paragraphs freely.
    about: [
      "I'm a filmmaker and video editor from Portugal. For six years I've made content across broadcast television, creative agencies, in-house brand teams, and EdTech.",
      "Today I'm a Video Editor at CXL, turning long-form educational content into social media assets and structured learning materials, working daily with an international, English-speaking team.",
      "Before that, I built Xpand IT's internal video department from the ground up and led end-to-end productions for brands including SONAE, CUF, and ONE: concept, filming, editing, color grading, and delivery. Television, with Shine Iberia and Endemol, taught me to work under pressure inside large production teams.",
      "Beyond the edit, I enjoy building efficient creative workflows and exploring AI-powered production tools that improve quality, speed, and consistency."
    ],
    cvFile: "",            // optional PDF, e.g. "media/_site/fabio-araujo-cv.pdf"
    // Empty links are hidden on the site.
    links: {
      instagram: "https://www.instagram.com/fabio.araujo99/",
      youtube: "https://www.youtube.com/@fabioaraujo574",
      linkedin: "https://www.linkedin.com/in/f%C3%A1bio-ara%C3%BAjo-7824b214b/",
      vimeo: ""
    }
  },

  // CV shown in the About section. Add, remove, or rename groups freely.
  cv: [
    {
      title: "Experience",
      items: [
        { what: "Video Editor", where: "CXL", when: "Mar 2025 - Present" },
        { what: "Filmmaker / Photographer", where: "Xpand IT", when: "Oct 2023 - Mar 2025" },
        { what: "Filmmaker / Photographer", where: "Adagietto", when: "Sep 2022 - Sep 2023" },
        { what: "Robotic Camera Operator", where: "Endemol (TVI)", when: "Sep 2021 - Sep 2022" },
        { what: "Robotic Camera Operator", where: "Shine Iberia (TVI)", when: "May 2021 - Aug 2021" },
        { what: "Sports Journalist", where: "Grupo Cofina: Correio da Manhã, CMTV, Record", when: "Sep 2020 - Mar 2021" }
      ]
    },
    {
      title: "Tools",
      items: [
        { what: "Adobe Premiere Pro" },
        { what: "DaVinci Resolve" },
        { what: "Adobe After Effects" },
        { what: "Adobe Photoshop & Lightroom" },
        { what: "Adobe Illustrator" },
        { what: "Blender" }
      ]
    },
    {
      title: "Clients",
      items: [
        { what: "SONAE" },
        { what: "CUF" },
        { what: "ONE" },
        { what: "LaCaixa" },
        { what: "Zurich" },
        { what: "Rosa&Teixeira" },
        { what: "TVI" }
      ]
    },
    {
      title: "Education",
      items: [
        { what: "Bachelor's in Social Communication", where: "ESEC, Polytechnic Institute of Coimbra", when: "2021" },
        { what: "Principles of Digital Marketing", where: "Google certification" }
      ]
    },
    {
      title: "Languages",
      items: [
        { what: "Portuguese", where: "Native" },
        { what: "English", where: "Advanced (C1, Linguaskill)" },
        { what: "Spanish", where: "Intermediate" },
        { what: "French", where: "Basic" }
      ]
    }
  ],

  // Filters shown on the site. Rename freely; each project uses one of these ids.
  // A category with no projects is hidden automatically.
  categories: [
    { id: "personal",  label: "Personal" },
    { id: "freelance", label: "Freelance" },
    { id: "cxl",       label: "CXL" },
    { id: "xpand",     label: "Xpand IT" },
    { id: "adagietto", label: "Adagietto" }
  ],

  // Work sections on the page, in order. Each shows the films from its categories.
  groups: [
    { title: "Personal & Freelance", categories: ["personal", "freelance"] },
    { title: "Jobs",                 categories: ["cxl", "xpand", "adagietto"] }
  ],

  // Films appear in their work group (featured ones first) and in the Index.
  // Photo series appear in "Stills" and in the Index.
  projects: [
    {
      slug: "piano-forum-2026",      // folder name in media/, also the link to this project
      type: "film",
      category: "freelance",
      featured: false,
      title: "Piano Forum 2026 with Ricardo Costa",
      year: "2026",
      role: "Ideation, Filming, Color Grading, Editing",
      client: "[CLIENT]",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/bbcLP7qq8nU/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=bbcLP7qq8nU",
      gallery: []
    },
    {
      slug: "supaserie-3",
      type: "film",
      category: "freelance",
      featured: false,
      title: "SUPASERIE #3 con Rodrigo Zalazar",
      year: "2025",
      role: "Filming, Color Grading",
      client: "SUPABROS",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/SOKJPrqEyws/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=SOKJPrqEyws",
      gallery: []
    },
    {
      slug: "supaserie-4",
      type: "film",
      category: "freelance",
      featured: false,
      title: "SUPASERIE #4 con Genaro Rodriguez",
      year: "2026",
      role: "Filming, Color Grading",
      client: "SUPABROS",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/TmTheiAbqCw/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=TmTheiAbqCw",
      gallery: []
    },
    {
      slug: "xpand-voices-of-innovation",
      type: "film",
      category: "xpand",
      featured: false,
      title: "Voices of Innovation - Xpand IT",
      year: "2024",
      role: "Ideation, Filming, Color Grading, Editing",
      client: "Xpand IT",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/fLwOu2kiTf8/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=fLwOu2kiTf8",
      gallery: []
    },
    {
      slug: "xpand-accessibility",
      type: "film",
      category: "xpand",
      featured: false,
      title: "Xpand IT - Accessibility",
      year: "2024",
      role: "Ideation, Filming, Color Grading, Editing",
      client: "Xpand IT",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/ZjXIYY6gT3o/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=ZjXIYY6gT3o",
      gallery: []
    },
    {
      slug: "xpand-jll-success-case",
      type: "film",
      category: "xpand",
      featured: false,
      title: "Xpand IT - JLL Success Case",
      year: "2024",
      role: "Ideation, Filming, Color Grading, Editing",
      client: "Xpand IT",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/7KYL6vO8-Vw/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=7KYL6vO8-Vw",
      gallery: []
    },
    {
      slug: "lacaixa-sempre-acompanhados",
      type: "film",
      category: "adagietto",
      featured: false,
      title: "LaCaixa - Sempre Acompanhados",
      year: "2023",
      role: "Camera Operator, Assistant Editor, Color Grading",
      client: "LaCaixa",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/DRKctvTGRSg/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=DRKctvTGRSg",
      gallery: []
    },
    {
      slug: "one-behind-the-scenes",
      type: "film",
      category: "adagietto",
      featured: false,
      title: "ONE - Behind the Scenes",
      year: "2023",
      role: "Editor, Color Grading",
      client: "ONE",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/71YvvHngGJk/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=71YvvHngGJk",
      gallery: []
    },
    {
      slug: "one-lifestyle-campaign",
      type: "film",
      category: "adagietto",
      featured: false,
      title: "ONE - Lifestyle Campaign",
      year: "2023",
      role: "Editor, Color Grading",
      client: "ONE",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/fE87Io1VQrg/hqdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=fE87Io1VQrg",
      aspect: "9:16",                // vertical video (YouTube Short)
      gallery: []
    },
    {
      slug: "cuf-medicina-dentaria",
      type: "film",
      category: "adagietto",
      featured: false,
      title: "CUF",
      year: "2023",
      role: "Editor, Camera Assistant",
      client: "CUF",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/DEMNyHj35LQ/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=DEMNyHj35LQ",
      gallery: []
    },
    {
      slug: "rosa-teixeira-case",
      type: "film",
      category: "adagietto",
      featured: false,
      title: "Rosa&Teixeira",
      year: "2024",
      role: "Camera Operator, Assistant Editor, Color Grading",
      client: "Rosa&Teixeira",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/sFgXe4C1rQQ/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=sFgXe4C1rQQ",
      gallery: []
    },
    {
      slug: "done-in-one-sec",
      type: "film",
      category: "adagietto",
      featured: false,
      title: "Done in ONE Sec.",
      year: "2023",
      role: "Editor",
      client: "[CLIENT]",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/5PRIpddSsP8/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=5PRIpddSsP8",
      gallery: []
    },
    {
      slug: "sonae-our-day",
      type: "film",
      category: "adagietto",
      featured: false,
      title: "SONAE Our Day",
      year: "2023",
      role: "Camera Operator, Editor",
      client: "SONAE",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/zPJJRwNvhRw/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=zPJJRwNvhRw",
      gallery: []
    },
    {
      slug: "zurich",
      type: "film",
      category: "adagietto",
      featured: false,
      title: "Zurich",
      year: "2023",
      role: "Camera Operator, Assistant Editor, Color Grading",
      client: "Zurich",
      description: "[One or two lines on the project.]",
      cover: "https://i.ytimg.com/vi/KYs8D9QTMvU/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=KYs8D9QTMvU",
      gallery: []
    },
    {
      slug: "inertia",
      type: "film",
      category: "personal",
      featured: false,
      title: "Inertia: The Art of Procrastination",
      year: "2026",
      role: "Ideation, Filming, Color Grading, Editing",
      client: "",
      description: "[One or two lines on the idea behind the film.]",
      cover: "https://i.ytimg.com/vi/8kJj86durxk/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=8kJj86durxk",
      gallery: []
    },
    {
      slug: "all-art-is-quite-useless",
      type: "film",
      category: "personal",
      featured: false,
      title: "“All art is quite useless.”",
      year: "2026",
      role: "Ideation, Filming, Color Grading, Editing",
      client: "",
      description: "Oscar Wilde, 1891 (The Picture of Dorian Gray). [One or two lines on the idea behind the film.]",
      cover: "https://i.ytimg.com/vi/4xBIifrSPcw/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=4xBIifrSPcw",
      gallery: []
    },
    {
      slug: "oasis-more-than-music",
      type: "film",
      category: "personal",
      featured: false,
      title: "Oasis: More Than Music, A Way of Life",
      year: "2026",
      role: "Ideation, Filming, Color Grading, Editing",
      client: "",
      description: "[One or two lines on the idea behind the film.]",
      cover: "https://i.ytimg.com/vi/Dhjq57tZiLE/hqdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=Dhjq57tZiLE",
      gallery: []
    },
    {
      slug: "diamante",
      type: "film",
      category: "personal",
      featured: false,
      title: "Diamante",
      year: "2023",
      role: "Camera & Editing Assistant",
      client: "",
      description: "Short film. [One or two lines on the story.]",
      cover: "https://i.ytimg.com/vi/GGHXwTyL7HM/maxresdefault.jpg",
      preview: "",
      video: "https://www.youtube.com/watch?v=GGHXwTyL7HM",
      gallery: []
    },
    {
      slug: "couples",
      type: "photo",
      category: "freelance",
      title: "Couples",
      year: "",
      role: "Photography",
      client: "",
      description: "Weddings, proposals, and a pregnancy shoot.",
      cover: "media/couples/DSC04721.jpg",   // shown on the series tab
      gallery: [                     // all photos, best first; the first ones also appear in Stills
        "media/couples/DSC04721.jpg",
        "media/couples/DSC3840.jpg",
        "media/couples/DSC04858.jpg",
        "media/couples/DSC4130.jpg",
        "media/couples/DSC04800.jpg",
        "media/couples/DSC3884.jpg",
        "media/couples/DSC04731.jpg",
        "media/couples/DSC7785.jpg",
        "media/couples/DSC05687.jpg",
        "media/couples/DSC4234.jpg",
        "media/couples/DSC04841.jpg",
        "media/couples/DSC6443.jpg",
        "media/couples/DSC04900.jpg",
        "media/couples/DSC4316.jpg",
        "media/couples/DSC04583.jpg",
        "media/couples/DSC8768.jpg",
        "media/couples/DSC04195.jpg",
        "media/couples/DSC05704.jpg",
        "media/couples/DSC7332.jpg",
        "media/couples/DSC04472.jpg",
        "media/couples/DSC04427.jpg",
        "media/couples/DSC3816.jpg",
        "media/couples/DSC04604.jpg",
        "media/couples/DSC8916.jpg",
        "media/couples/DSC05516.jpg",
        "media/couples/DSC04395.jpg",
        "media/couples/DSC4160.jpg",
        "media/couples/DSC6264.jpg",
        "media/couples/DSC3830.jpg",
        "media/couples/DSC4273-2.jpg",
        "media/couples/DSC6479.jpg",
        "media/couples/DSC3760.jpg",
        "media/couples/DSC7741.jpg",
        "media/couples/DSC8848.jpg",
        "media/couples/DSC4128.jpg",
        "media/couples/DSC3933-2.jpg",
        "media/couples/DSC6321.jpg",
        "media/couples/DSC4200.jpg",
        "media/couples/DSC7858.jpg",
        "media/couples/DSC3955.jpg",
        "media/couples/DSC4167.jpg",
        "media/couples/DSC3741-2.jpg",
        "media/couples/DSC3805.jpg",
        "media/couples/DSC3811.jpg",
        "media/couples/DSC3818.jpg",
        "media/couples/DSC3852.jpg",
        "media/couples/DSC3915.jpg",
        "media/couples/DSC3939.jpg",
        "media/couples/DSC3957-2.jpg",
        "media/couples/DSC3972.jpg",
        "media/couples/DSC3973.jpg",
        "media/couples/DSC3981.jpg",
        "media/couples/DSC3985.jpg",
        "media/couples/DSC4014.jpg",
        "media/couples/DSC4047.jpg",
        "media/couples/DSC4051.jpg",
        "media/couples/DSC4101.jpg",
        "media/couples/DSC4119.jpg",
        "media/couples/DSC4132.jpg",
        "media/couples/DSC4169.jpg",
        "media/couples/DSC4171.jpg",
        "media/couples/DSC4193.jpg",
        "media/couples/DSC4225.jpg",
        "media/couples/DSC4236.jpg",
        "media/couples/DSC4269-2.jpg",
        "media/couples/DSC4313-2.jpg",
        "media/couples/DSC6035.jpg",
        "media/couples/DSC6230.jpg",
        "media/couples/DSC6362.jpg",
        "media/couples/DSC6364.jpg",
        "media/couples/DSC6455.jpg",
        "media/couples/DSC6471.jpg",
        "media/couples/DSC6556.jpg",
        "media/couples/DSC6873.jpg",
        "media/couples/DSC7182.jpg",
        "media/couples/DSC7199.jpg",
        "media/couples/DSC7210.jpg",
        "media/couples/DSC7211.jpg",
        "media/couples/DSC7237.jpg",
        "media/couples/DSC7240.jpg",
        "media/couples/DSC7250.jpg",
        "media/couples/DSC7271-2.jpg",
        "media/couples/DSC7277.jpg",
        "media/couples/DSC7287-2.jpg",
        "media/couples/DSC7306.jpg",
        "media/couples/DSC7552.jpg",
        "media/couples/DSC7772.jpg",
        "media/couples/DSC7789.jpg",
        "media/couples/DSC7797.jpg",
        "media/couples/DSC7882.jpg",
        "media/couples/DSC7942.jpg",
        "media/couples/DSC8676.jpg",
        "media/couples/DSC8695.jpg",
        "media/couples/DSC8705.jpg",
        "media/couples/DSC8733.jpg",
        "media/couples/DSC8763.jpg",
        "media/couples/DSC8779.jpg",
        "media/couples/DSC8795.jpg",
        "media/couples/DSC8803.jpg",
        "media/couples/DSC8808.jpg",
        "media/couples/DSC8836.jpg",
        "media/couples/DSC8856.jpg",
        "media/couples/DSC8865.jpg",
        "media/couples/DSC8876.jpg",
        "media/couples/DSC04030.jpg",
        "media/couples/DSC04057.jpg",
        "media/couples/DSC04069.jpg",
        "media/couples/DSC04073.jpg",
        "media/couples/DSC04092.jpg",
        "media/couples/DSC04097.jpg",
        "media/couples/DSC04122.jpg",
        "media/couples/DSC04125.jpg",
        "media/couples/DSC04131.jpg",
        "media/couples/DSC04145.jpg",
        "media/couples/DSC04163.jpg",
        "media/couples/DSC04165.jpg",
        "media/couples/DSC04170.jpg",
        "media/couples/DSC04174.jpg",
        "media/couples/DSC04190.jpg",
        "media/couples/DSC04214.jpg",
        "media/couples/DSC04236.jpg",
        "media/couples/DSC04250.jpg",
        "media/couples/DSC04286.jpg",
        "media/couples/DSC04303.jpg",
        "media/couples/DSC04306.jpg",
        "media/couples/DSC04307.jpg",
        "media/couples/DSC04315.jpg",
        "media/couples/DSC04330.jpg",
        "media/couples/DSC04338.jpg",
        "media/couples/DSC04343.jpg",
        "media/couples/DSC04349.jpg",
        "media/couples/DSC04362.jpg",
        "media/couples/DSC04373.jpg",
        "media/couples/DSC04397.jpg",
        "media/couples/DSC04403.jpg",
        "media/couples/DSC04408.jpg",
        "media/couples/DSC04430.jpg",
        "media/couples/DSC04437.jpg",
        "media/couples/DSC04477.jpg",
        "media/couples/DSC04538.jpg",
        "media/couples/DSC04546.jpg",
        "media/couples/DSC04548.jpg",
        "media/couples/DSC04553.jpg",
        "media/couples/DSC04557.jpg",
        "media/couples/DSC04578.jpg",
        "media/couples/DSC04592.jpg",
        "media/couples/DSC04596.jpg",
        "media/couples/DSC04636.jpg",
        "media/couples/DSC04638.jpg",
        "media/couples/DSC04683.jpg",
        "media/couples/DSC04696.jpg",
        "media/couples/DSC04698.jpg",
        "media/couples/DSC04705.jpg",
        "media/couples/DSC04709.jpg",
        "media/couples/DSC04723.jpg",
        "media/couples/DSC04728.jpg",
        "media/couples/DSC04788.jpg",
        "media/couples/DSC04792.jpg",
        "media/couples/DSC04796.jpg",
        "media/couples/DSC04798.jpg",
        "media/couples/DSC04805.jpg",
        "media/couples/DSC04811.jpg",
        "media/couples/DSC04815.jpg",
        "media/couples/DSC04821.jpg",
        "media/couples/DSC04825.jpg",
        "media/couples/DSC04831.jpg",
        "media/couples/DSC04850.jpg",
        "media/couples/DSC04864.jpg",
        "media/couples/DSC04869.jpg",
        "media/couples/DSC04877.jpg",
        "media/couples/DSC04886.jpg",
        "media/couples/DSC04887.jpg",
        "media/couples/DSC04905.jpg",
        "media/couples/DSC05009.jpg",
        "media/couples/DSC05021.jpg",
        "media/couples/DSC05060.jpg",
        "media/couples/DSC05069.jpg",
        "media/couples/DSC05166.jpg",
        "media/couples/DSC05173.jpg",
        "media/couples/DSC05177.jpg",
        "media/couples/DSC05178.jpg",
        "media/couples/DSC05220.jpg",
        "media/couples/DSC05232.jpg",
        "media/couples/DSC05237.jpg",
        "media/couples/DSC05243.jpg",
        "media/couples/DSC05258.jpg",
        "media/couples/DSC05271.jpg",
        "media/couples/DSC05277.jpg",
        "media/couples/DSC05338.jpg",
        "media/couples/DSC05365.jpg",
        "media/couples/DSC05409.jpg",
        "media/couples/DSC05514.jpg",
        "media/couples/DSC05526.jpg",
        "media/couples/DSC05543.jpg",
        "media/couples/DSC05546.jpg",
        "media/couples/DSC05555.jpg",
        "media/couples/DSC05576.jpg",
        "media/couples/DSC05617.jpg",
        "media/couples/DSC05660.jpg",
        "media/couples/DSC05671.jpg",
        "media/couples/DSC05690.jpg",
        "media/couples/DSC05695.jpg",
        "media/couples/DSC05696.jpg",
        "media/couples/DSC05701.jpg",
        "media/couples/DSC05719.jpg",
        "media/couples/DSC05724.jpg",
        "media/couples/DSC05813.jpg"
      ]
    },
    {
      slug: "freelance-photography",
      type: "photo",
      category: "freelance",
      title: "Freelance",
      year: "",
      role: "Photography",
      client: "",
      description: "[One or two lines about this work.]",
      cover: "media/freelance-photography/DSC5581.jpg",   // shown on the series tab
      gallery: [                     // all photos, best first; the first ones also appear in Stills
        "media/freelance-photography/DSC5581.jpg",
        "media/freelance-photography/DSC9950.jpg",
        "media/freelance-photography/DSC5748.jpg",
        "media/freelance-photography/DSC9725.jpg",
        "media/freelance-photography/DSC5770.jpg",
        "media/freelance-photography/DSC9917.jpg",
        "media/freelance-photography/DSC5679.jpg",
        "media/freelance-photography/DSC5444.jpg",
        "media/freelance-photography/DSC9710.jpg",
        "media/freelance-photography/DSC5631.jpg",
        "media/freelance-photography/DSC9920.jpg",
        "media/freelance-photography/DSC5790.jpg",
        "media/freelance-photography/DSC5351.jpg",
        "media/freelance-photography/DSC9693.jpg",
        "media/freelance-photography/DSC5959.jpg",
        "media/freelance-photography/DSC9943.jpg",
        "media/freelance-photography/DSC5599.jpg",
        "media/freelance-photography/DSC5278.jpg",
        "media/freelance-photography/DSC5282.jpg",
        "media/freelance-photography/DSC9744.jpg",
        "media/freelance-photography/DSC5537.jpg",
        "media/freelance-photography/DSC6018.jpg",
        "media/freelance-photography/DSC9901.jpg",
        "media/freelance-photography/DSC5743.jpg",
        "media/freelance-photography/DSC5280.jpg",
        "media/freelance-photography/DSC5286.jpg",
        "media/freelance-photography/DSC5288.jpg",
        "media/freelance-photography/DSC5296.jpg",
        "media/freelance-photography/DSC5300.jpg",
        "media/freelance-photography/DSC5311.jpg",
        "media/freelance-photography/DSC5313.jpg",
        "media/freelance-photography/DSC5314.jpg",
        "media/freelance-photography/DSC5325.jpg",
        "media/freelance-photography/DSC5343.jpg",
        "media/freelance-photography/DSC5344.jpg",
        "media/freelance-photography/DSC5347.jpg",
        "media/freelance-photography/DSC5352.jpg",
        "media/freelance-photography/DSC5359.jpg",
        "media/freelance-photography/DSC5360.jpg",
        "media/freelance-photography/DSC5381.jpg",
        "media/freelance-photography/DSC5398.jpg",
        "media/freelance-photography/DSC5418.jpg",
        "media/freelance-photography/DSC5432.jpg",
        "media/freelance-photography/DSC5451.jpg",
        "media/freelance-photography/DSC5458.jpg",
        "media/freelance-photography/DSC5460.jpg",
        "media/freelance-photography/DSC5471.jpg",
        "media/freelance-photography/DSC5476.jpg",
        "media/freelance-photography/DSC5489.jpg",
        "media/freelance-photography/DSC5494.jpg",
        "media/freelance-photography/DSC5507.jpg",
        "media/freelance-photography/DSC5512.jpg",
        "media/freelance-photography/DSC5529.jpg",
        "media/freelance-photography/DSC5533.jpg",
        "media/freelance-photography/DSC5542.jpg",
        "media/freelance-photography/DSC5554.jpg",
        "media/freelance-photography/DSC5565.jpg",
        "media/freelance-photography/DSC5577.jpg",
        "media/freelance-photography/DSC5615.jpg",
        "media/freelance-photography/DSC5624.jpg",
        "media/freelance-photography/DSC5626.jpg",
        "media/freelance-photography/DSC5635.jpg",
        "media/freelance-photography/DSC5645.jpg",
        "media/freelance-photography/DSC5647.jpg",
        "media/freelance-photography/DSC5660.jpg",
        "media/freelance-photography/DSC5665.jpg",
        "media/freelance-photography/DSC5668.jpg",
        "media/freelance-photography/DSC5683.jpg",
        "media/freelance-photography/DSC5700.jpg",
        "media/freelance-photography/DSC5711.jpg",
        "media/freelance-photography/DSC5745.jpg",
        "media/freelance-photography/DSC5754.jpg",
        "media/freelance-photography/DSC5760.jpg",
        "media/freelance-photography/DSC5796.jpg",
        "media/freelance-photography/DSC5822.jpg",
        "media/freelance-photography/DSC5828.jpg",
        "media/freelance-photography/DSC5832.jpg",
        "media/freelance-photography/DSC5834.jpg",
        "media/freelance-photography/DSC5837.jpg",
        "media/freelance-photography/DSC5841.jpg",
        "media/freelance-photography/DSC5869.jpg",
        "media/freelance-photography/DSC5878.jpg",
        "media/freelance-photography/DSC5884.jpg",
        "media/freelance-photography/DSC5900.jpg",
        "media/freelance-photography/DSC5905.jpg",
        "media/freelance-photography/DSC5908.jpg",
        "media/freelance-photography/DSC5912.jpg",
        "media/freelance-photography/DSC5915.jpg",
        "media/freelance-photography/DSC5929.jpg",
        "media/freelance-photography/DSC5956.jpg",
        "media/freelance-photography/DSC5965.jpg",
        "media/freelance-photography/DSC5967.jpg",
        "media/freelance-photography/DSC5977.jpg",
        "media/freelance-photography/DSC5999.jpg",
        "media/freelance-photography/DSC6012.jpg",
        "media/freelance-photography/DSC6028.jpg",
        "media/freelance-photography/DSC9697.jpg",
        "media/freelance-photography/DSC9707.jpg",
        "media/freelance-photography/DSC9721.jpg",
        "media/freelance-photography/DSC9735.jpg",
        "media/freelance-photography/DSC9740.jpg",
        "media/freelance-photography/DSC9875.jpg",
        "media/freelance-photography/DSC9908.jpg",
        "media/freelance-photography/DSC9940.jpg",
        "media/freelance-photography/DSC9958.jpg"
      ]
    },
    {
      slug: "personal-photography",
      type: "photo",
      category: "personal",
      title: "Personal",
      year: "",
      role: "Photography",
      client: "",
      description: "[One or two lines about this work.]",
      cover: "media/personal-photography/DSC1054.jpg",   // shown on the series tab
      gallery: [                     // all photos, best first; the first ones also appear in Stills
        "media/personal-photography/DSC1054.jpg",
        "media/personal-photography/DSC0603.jpg",
        "media/personal-photography/DSC5233.jpg",
        "media/personal-photography/DSC4794.jpg",
        "media/personal-photography/DSC1243.jpg",
        "media/personal-photography/DSC5035.jpg",
        "media/personal-photography/DSC1080.jpg",
        "media/personal-photography/DSC1422.jpg",
        "media/personal-photography/DSC4519.jpg",
        "media/personal-photography/DSC1024.jpg",
        "media/personal-photography/DSC1286.jpg",
        "media/personal-photography/DSC5247.jpg",
        "media/personal-photography/DSC1032.jpg",
        "media/personal-photography/DSC4619.jpg",
        "media/personal-photography/DSC0661.jpg",
        "media/personal-photography/DSC5069.jpg",
        "media/personal-photography/DSC1110.jpg",
        "media/personal-photography/DSC4643.jpg",
        "media/personal-photography/DSC1345.jpg",
        "media/personal-photography/DSC5055.jpg",
        "media/personal-photography/DSC0629.jpg",
        "media/personal-photography/DSC0678.jpg",
        "media/personal-photography/DSC0715.jpg",
        "media/personal-photography/DSC0726.jpg",
        "media/personal-photography/DSC0758.jpg",
        "media/personal-photography/DSC0760.jpg",
        "media/personal-photography/DSC0773.jpg",
        "media/personal-photography/DSC0815.jpg",
        "media/personal-photography/DSC0918.jpg",
        "media/personal-photography/DSC1038.jpg",
        "media/personal-photography/DSC1057.jpg",
        "media/personal-photography/DSC1064.jpg",
        "media/personal-photography/DSC1069.jpg",
        "media/personal-photography/DSC1075.jpg",
        "media/personal-photography/DSC1129.jpg",
        "media/personal-photography/DSC1146.jpg",
        "media/personal-photography/DSC1153.jpg",
        "media/personal-photography/DSC1172.jpg",
        "media/personal-photography/DSC1236.jpg",
        "media/personal-photography/DSC1272.jpg",
        "media/personal-photography/DSC1329.jpg",
        "media/personal-photography/DSC1340.jpg",
        "media/personal-photography/DSC1392.jpg",
        "media/personal-photography/DSC1425.jpg",
        "media/personal-photography/DSC4378.jpg",
        "media/personal-photography/DSC4423.jpg",
        "media/personal-photography/DSC4439.jpg",
        "media/personal-photography/DSC4518.jpg",
        "media/personal-photography/DSC4573.jpg",
        "media/personal-photography/DSC4586.jpg",
        "media/personal-photography/DSC4672.jpg",
        "media/personal-photography/DSC4699.jpg",
        "media/personal-photography/DSC4813.jpg",
        "media/personal-photography/DSC4880.jpg",
        "media/personal-photography/DSC4892.jpg",
        "media/personal-photography/DSC4895.jpg",
        "media/personal-photography/DSC4916.jpg",
        "media/personal-photography/DSC4957.jpg",
        "media/personal-photography/DSC4987.jpg",
        "media/personal-photography/DSC5127.jpg",
        "media/personal-photography/DSC5158.jpg",
        "media/personal-photography/DSC5194.jpg",
        "media/personal-photography/DSC5248.jpg",
        "media/personal-photography/DSC5263.jpg",
        "media/personal-photography/DSC5271.jpg"
      ]
    }
  ]
};
